name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write        

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Needed just to run dotnet CLI

      - name: Build project
        run: dotnet build -f net48 -c Release

      - name: Archive build output
        run: |
          mkdir artifact
          Compress-Archive -Path .\bin\* -DestinationPath artifact/OnnxInference.zip
  
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          files: artifact/OnnxInference.zip
